services:
  - type: web
    name: telegram-ai-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
